# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 10:57
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170331_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', primary_key=True, serialize=False),
        ),
    ]
